name: 🐞 Bug
description: Create a report to help us improve
title: "[BUG] - "
labels: []
assignees: []
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How do you reproduce this bug?
      description: Please provide a list of steps to cause this issue
      placeholder: |
        1. Navigate to ...
        2. Click on ...
        3. See this happen ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please explain what you think should be happening
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    attributes:
      label: API Version
      description: Please list the API version you are using
      placeholder: "0.3.2"
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Which PHP version are you using
      placeholder: "8.0.11"
    validations:
      required: true
  - type: input
    attributes:
      label: Database & version
      description: Which database & version are you using
      placeholder: "10.5.12-MariaDB"
    validations:
      required: true
  - type: input
    attributes:
      label: Webserver version
      description: List the webserver you are using
      placeholder: "Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/8.0.11"
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: List the browser you are using
      placeholder: "Chrome 96.0.4664.110"
    validations:
      required: true
  - type: input
    attributes:
      label: Handler
      description: List what intergration you are using
      placeholder: "phpvms5"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Please add any additional information you belive may be helpful in resolving this bug
    validations:
      required: false
